# Generated by Django 5.0.7 on 2024-08-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_publish_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_data',
        ),
        migrations.AddField(
            model_name='product',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
